typography_spectrum: 0.8942156403791159
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15962571231648326
  lightness: 0.025654220953583717
  saturation: 0.7474137526005507
  rhythmicContrast: 0.3571008702274412
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7433
analytics:
  google: null
  facebook: null
  twitter: null
name: testeeri
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Getting Started on The Grid
    id: 18d1601b-db7c-4680-82c7-a2076b2fa299
    type: content
favicon: null
title: Fintrav
description: Travellers Online
purpose: []
